from decimal import Decimal


ZERO_DECIMAL = Decimal("0.00")
MIN_TRANSFER_AMOUNT = Decimal("0.01")
MAX_TRANSFER_AMOUNT_PER_RECIPIENT = Decimal("1000000")

TIN_MIN_LENGTH = 10
TIN_MAX_LENGTH = 12

MAX_RECIPIENTS_COUNT = 100
