version: '3.8'

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 3
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  money_transfer:
    build: .
    restart: always
    env_file: .env
    volumes:
      - "static_volume:/app/static/"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/admin/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "static_volume:/app/static"
    restart: always
    ports:
      - "8080:80"
    depends_on:
        money_transfer:
            condition: service_healthy

volumes:
  postgresql_data:
    driver: local
  static_volume:
    driver: local
