# Generated by Django 5.1.1 on 2024-09-26 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tin",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.RegexValidator(
                        message="Taxpayer Identification Number must contain only digits",
                        regex="^\\d+$",
                    ),
                ],
            ),
        ),
    ]
