# Generated by Django 5.1.1 on 2024-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_tin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="account",
            new_name="balance",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
